class User(Base):
    __tablename__ = "user"
    uuidcode=uuid.uuid4()

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    cognito_id = Column(UUID(as_uuid=True), nullable=False)
    account_id = Column(BigInteger, ForeignKey('account.id'), nullable=False)
    name = Column(String, nullable=False)
    address = Column(Text, nullable=False)
    email = Column(String, nullable=False)
    phone_number = Column(String, nullable=False)
    employee_id = Column(String, nullable=False)
    profile_activated = Column(Boolean, nullable=False)
    profile_picture = Column(String,nullable=True)
    location = Column(String, nullable=False)
    created_at = Column(DateTime(timezone=True),
                        server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    profile_activation_date = Column(DateTime(timezone=True), nullable=True)
    joining_date = Column(Date, nullable=True)
    role_start_date = Column(Date, nullable=True)
    current_role_id = Column(
        BigInteger, ForeignKey('jobrole.id'), nullable=True)
    profile_picture_url = Column(String, nullable=True)
    profile_pic_url_expiry = Column(DateTime(timezone=True), nullable=True)
    # gender = Column(String, nullable=True)
    gender = Column(String, nullable=True)
    user_character = Column(String, nullable=False)
    employement_type = Column(String, nullable=False,server_default=text("full"))
    designation = Column(BigInteger,
        ForeignKey('md_designation.id'),
        nullable=True)
    status = Column(BigInteger,server_default=text("1"), nullable=False)
    surname = Column(String, nullable=True)
    zone = Column(String, nullable=False, server_default='central')
    geo = Column(String, nullable=True)
    cluster = Column(String, nullable=True)
    branch = Column(String, nullable=True)
    city = Column(BigInteger,ForeignKey('md_city.id'), nullable=True)
    state = Column(BigInteger,ForeignKey('md_state.id'), nullable=True)
    date_of_birth = Column(Date, nullable=True)
    debug = Column(Boolean)
    gender_id = Column(BigInteger,ForeignKey('md_gender.id'), nullable=True)
    employment_type_id = Column(BigInteger,ForeignKey('md_employement_type.id'), nullable=True)
    app_language_id = Column(BigInteger,ForeignKey('md_app_languages.id'), nullable=True)
    full_name = Column(String, nullable=True)
    user_type_id = Column(BigInteger,ForeignKey('md_user_type.id'), nullable=True)
    performance_label = Column(String, nullable=True)
    residency_label = Column(String, nullable=True)

    # relationship
    account = relationship("Account")
    preferred_languages = relationship("Mdlanguage", secondary="user_language")
    current_role = relationship("Jobrole")
    mdesignation = relationship("Mdesignation")
    mdcity = relationship("Mdcity", foreign_keys=[city])
    mdstate = relationship("Mdstate", foreign_keys=[state])
    mdgender = relationship("MdGender", foreign_keys=[gender_id])
    mdemploymenttype = relationship("MdEmployeemntType", foreign_keys=[employment_type_id])
    mdapplanguage = relationship("Mdapplanguages", foreign_keys=[app_language_id])
    user_type = relationship("MdUserType", foreign_keys=[user_type_id])
    # account_access = relationship("UserAccountAccess", back_populates="user")